export { handleRectangleDragEnd } from './handleRectangleDragEnd'
export { handlePolygonDragEnd } from './handlePolygonDragEnd'
export { handleDotDragEnd } from './handleDotDragEnd'
export { handleLineDragEnd } from './handleLineDragEnd'
export { handleCircleDragEnd } from './handleCircleDragEnd'
export { handleFreehandDragEnd } from './handleFreehandDragEnd'
